[WEEEK-17] [WEEEK-3]

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -88,7 +88,7 @@ jobs:
             --label "release" \
             --title "${{ steps.gen.outputs.release_name }}" \
             --body "${{ steps.gen.outputs.changelog }}")
-          echo "pull_request_link=PR_LINK" >> "$GITHUB_OUTPUT"
+          echo "pull_request_link=$PR_LINK" >> "$GITHUB_OUTPUT"
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
@@ -96,4 +96,32 @@ jobs:
         run: gh pr merge --merge --auto "${{ steps.cprdm.outputs.pull_request_link }}"
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Check PR Status
+        id: cprs
+        run: |
+          PR_VIEW=$(gh pr view "${{ steps.cprdm.outputs.pull_request_link }}" \
+          --json "state,body,title")
+          
+          STATE=$(jq -r .state $PR_VIEW)
+          
+          if [ "$STATE" != "MERGED" ]; then
+            echo "PR ${{ steps.cprdm.outputs.pull_request_link }} not merged (merged=$STATE). Exiting with error."
+            exit 1
+          fi
+          
+          BODY=$(jq -r .body $PR_VIEW)
+          TITLE=$(jq -r .title $PR_VIEW)
+          
+          echo "pull_request_body=$BODY" >> "$GITHUB_OUTPUT"
+          echo "pull_request_title=$TITLE" >> "$GITHUB_OUTPUT"
+
+      - name: Run Integration Release with Weeek
+        run: npx tsx scripts/weeek-release.ts
+        env:
+          WEEEK_API_KEY: ${{ secrets.WEEEK_API_KEY }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_PR_BODY: ${{ steps.cprs.outputs.pull_request_body }}
+          GITHUB_PR_TITLE: ${{ steps.cprs.outputs.pull_request_title }}
+
 
